#!/bin/bash

# GitHub repository: https://github.com/fearlessdots/auto-update-packages
# RUN THIS SCRIPT AS ROOT
# Valid arguments:
# 0 ==> disable autoupdatepackages.service
# 1 ==> enable autoupdatepackages.service

# Shell display functions
show_info(){
	echo "$(tput setaf 26)[  AutoUpdatePackages  ]$(tput sgr0) $(tput setaf 250)$1$(tput sgr0)"
}

show_attention()
{
	echo "$(tput setaf 9)[ ATTENTION ]$(tput sgr0) $(tput setaf 7)$1$(tput sgr0)"
}

finish_program()
{
	# $1 is the exit code
	exit $1
}

#
##
#

if [ "$1" -eq 0 ]
then
	show_info "Disabling autoupdatepackages service"
	systemctl disable autoupdatepackages.service
	finish_program 0
elif [ "$1" -eq 1 ]
then
	show_info "Enabling autoupdatepackages service"
	systemctl enable autoupdatepackages.service
	finish_program 1
else
	show_attention "Invalid argument"
	finish_program 1
fi
