#!/bin/bash

# GitHub repository: https://github.com/fearlessdots/auto-update-packages
# RUN THIS SCRIPT AS ROOT
# Warning: changing the values of the variables in this script may render it unworkable.

# The values below refer to the installation directories. If needed to change them,
# do it cautiously.
PROGRAM_DIR=/usr/share/auto-update-packages
EXEC_DIR=/usr/bin
LOG_DIR=$PROGRAM_DIR/logs
SYSMD_DIR=/usr/lib/systemd/system

# Shell display functions
show_info(){
	echo "$(tput setaf 26)[  AutoUpdatePackages  ]$(tput sgr0) $(tput setaf 250)$1$(tput sgr0)"
}

show_attention()
{
	echo "$(tput setaf 9)[ ATTENTION ]$(tput sgr0) $(tput setaf 7)$1$(tput sgr0)"
}

show_success(){
	echo "$(tput setaf 14)[ SUCCESS ]$(tput sgr0) $(tput setaf 26)$1$(tput sgr0)"
}

finish_program()
{
	# $1 is the exit code
	exit $1
}

#
##
#

show_info "Running uninstallation script..."

sleep 1

if [ -d $PROGRAM_DIR ]
then
	rm -rf $PROGRAM_DIR
	show_success "Configuration directory removed"
else
	show_attention "Configuration directory not found!"
fi

sleep 1

if [ -f $EXEC_DIR/auto-update-packages ]
then
	rm $EXEC_DIR/auto-update-packages
	show_success "Executable removed"
else
	show_attention "Executable not found!"
fi

sleep 1

if [ -f $SYSMD_DIR/autoupdatepackages.service ]
then
	systemctl disable autoupdatepackages.service
	systemctl stop autoupdatepackages.service
	rm $SYSMD_DIR/autoupdatepackages.service
	show_success "Systemd service disabled and removed"
else
	show_attention "Systemd service not found!"
fi

finish_program 0
